// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdyA8XUvuhxH5ASido38ju6r_HzxQvohI',
    appId: '1:1006841524003:web:196c401b550de56d5ce696',
    messagingSenderId: '1006841524003',
    projectId: 'pkart-homeautomation',
    authDomain: 'pkart-homeautomation.firebaseapp.com',
    storageBucket: 'pkart-homeautomation.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74KWS7lhO0YJHSQZ7rWqvunriv687LUs',
    appId: '1:1006841524003:android:a5e9605258693e925ce696',
    messagingSenderId: '1006841524003',
    projectId: 'pkart-homeautomation',
    storageBucket: 'pkart-homeautomation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rHlBHEHY6eD90WUtiucGhaBnbR2Gbsc',
    appId: '1:1006841524003:ios:5705f2090d81ffc75ce696',
    messagingSenderId: '1006841524003',
    projectId: 'pkart-homeautomation',
    storageBucket: 'pkart-homeautomation.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rHlBHEHY6eD90WUtiucGhaBnbR2Gbsc',
    appId: '1:1006841524003:ios:5705f2090d81ffc75ce696',
    messagingSenderId: '1006841524003',
    projectId: 'pkart-homeautomation',
    storageBucket: 'pkart-homeautomation.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdyA8XUvuhxH5ASido38ju6r_HzxQvohI',
    appId: '1:1006841524003:web:be34dfe6661e504b5ce696',
    messagingSenderId: '1006841524003',
    projectId: 'pkart-homeautomation',
    authDomain: 'pkart-homeautomation.firebaseapp.com',
    storageBucket: 'pkart-homeautomation.firebasestorage.app',
  );

}